---
version: '1.0'
box: abs

name: asl

# pipeline -> stage -> tasks
vars:
  group.id: jkasl
  artifact.id: ${meta.name}

stages:
  - name: pkg
    tasks:
      - task.id: semver
      - task.id: opspkg
        artifact.id: ${meta.name}
        fileset.dir: ${ws.dir}
        fileset.includes: 'lib/**/*,scripts/**/*,tool/**/*,VERSION'

  - name: artifact
    tasks:
      - task.id: ftpartifact
        scm.type: git
        artifact.lane: jenkins
        fileset.dir: ${ws.dir}
        fileset.includes: ${meta.name}-*.tar.gz

pipelines:
  - name: dev
    stages:
      - pkg
      - artifact

default: dev
